"""empty message

Revision ID: b258c0a2f4ba
Revises: 
Create Date: 2026-07-09 22:17:37.531383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b258c0a2f4ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celdas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_celda', sa.String(length=10), nullable=False),
    sa.Column('tipo_celda', sa.String(length=30), nullable=False),
    sa.Column('ocupada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('celdas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_celdas_codigo_celda'), ['codigo_celda'], unique=True)

    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_apertura', sa.String(length=5), nullable=False),
    sa.Column('hora_cierre', sa.String(length=5), nullable=False),
    sa.Column('permitir_festivos', sa.Boolean(), nullable=False),
    sa.Column('tiempo_maximo', sa.Integer(), nullable=False),
    sa.Column('accion_exceso', sa.String(length=30), nullable=False),
    sa.Column('celdas_admin', sa.Integer(), nullable=False),
    sa.Column('celdas_operativas', sa.Integer(), nullable=False),
    sa.Column('celdas_movilidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('USUARIO', 'VIGILANTE', 'ADMINISTRADOR', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('visitantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=10), nullable=False),
    sa.Column('area_visitada', sa.String(length=100), nullable=False),
    sa.Column('motivo_visita', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitantes_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitantes_placa_vehiculo'), ['placa_vehiculo'], unique=False)

    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_auditoria_fecha'), ['fecha'], unique=False)

    op.create_table('novedades_vigilante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jornada', sa.String(length=20), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('total_entradas', sa.Integer(), nullable=True),
    sa.Column('total_salidas', sa.Integer(), nullable=True),
    sa.Column('total_visitantes', sa.Integer(), nullable=True),
    sa.Column('total_novedades', sa.Integer(), nullable=True),
    sa.Column('observaciones_finales', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiculos_placa'), ['placa'], unique=True)

    op.create_table('accesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=15), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=25), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('celda_id', sa.Integer(), nullable=True),
    sa.Column('celda_asignada', sa.String(length=10), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('observaciones_salida', sa.String(length=255), nullable=True),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celda_id'], ['celdas.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accesos_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_accesos_placa'), ['placa'], unique=False)

    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('tipo_novedad', sa.String(length=50), nullable=False),
    sa.Column('placa_relacionada', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_novedad', sa.Date(), nullable=False),
    sa.Column('fecha_registro_sistema', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novedades_placa_relacionada'), ['placa_relacionada'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novedades_placa_relacionada'))

    op.drop_table('novedades')
    with op.batch_alter_table('accesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accesos_placa'))
        batch_op.drop_index(batch_op.f('ix_accesos_fecha_hora'))

    op.drop_table('accesos')
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculos_placa'))

    op.drop_table('vehiculos')
    op.drop_table('turnos')
    op.drop_table('novedades_vigilante')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_fecha'))

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitantes_placa_vehiculo'))
        batch_op.drop_index(batch_op.f('ix_visitantes_documento'))

    op.drop_table('visitantes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    op.drop_table('configuraciones')
    with op.batch_alter_table('celdas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_celdas_codigo_celda'))

    op.drop_table('celdas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
